### PR TITLE
Align PR template with other repos

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Formats the PR template to align with PR templates on other repos

### How to review 
Check changes

### CODE REVIEW

**Comment by rmccar** [comment]
[eq-app-deploy-image rename default branch](https://trello.com/c/UO7BnCm1/5590-eq-app-deploy-image-rename-default-branch)

**Review by creativeappdevamit — COMMENTED** [review]
@rmccar - There doesn't seems to have any change other than formatting.

**Comment by rmccar** [comment]
> @rmccar - There doesn't seems to have any change other than formatting.

Yeah thats all the change is. I noticed some whitespace etc when doing the branch rename so just raised a PR to fix it

**Comment by creativeappdevamit** [comment]
> > @rmccar - There doesn't seems to have any change other than formatting.
> 
> Yeah thats all the change is. I noticed some whitespace etc when doing the branch rename so just raised a PR to fix it

👍

**Review by creativeappdevamit — APPROVED** [review]
Tested and it looks good to me

**Review by Yuyuutsu — APPROVED** [review]

**Pull request merged**
